name: Prasanth test workflow

on:
  push:
    branches: [main]

jobs:
  first-job:
    runs-on: ubuntu-latest  
    steps:
      - name: Say hello
        uses: actions/checkout@v4


      - name: setup a python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.12'
      
      - name: Run health  check script
        run: python3 health_check.py    


        


